import { MapPin, Pencil, Plus, ShieldCheck, Tag, Trash2, type LucideIcon } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { categoriesApi, locationsApi, rolesApi } from '../lib/catalogApi'
import type { Category, Location, Role } from '../types/inventory'
import { ConfirmDialog } from './ConfirmDialog'
import { Modal } from './Modal'

type Kind='categories'|'locations'|'roles'
type Item=Category|Location|Role
const api={categories:categoriesApi,locations:locationsApi,roles:rolesApi}
export function SettingsPanel(){
  const [categories,setCategories]=useState<Category[]>([]),[locations,setLocations]=useState<Location[]>([]),[roles,setRoles]=useState<Role[]>([]),[editing,setEditing]=useState<{kind:Kind;item:Item|null}|null>(null),[deleting,setDeleting]=useState<{kind:Kind;item:Item}|null>(null)
  const [name,setName]=useState(''),[detail,setDetail]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const load=async()=>{setLoading(true);setError('');try{const [c,l,r]=await Promise.all([categoriesApi.list(),locationsApi.list(),rolesApi.list()]);setCategories(c);setLocations(l);setRoles(r)}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar la configuración.')}finally{setLoading(false)}}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[])
  const open=(kind:Kind,item:Item|null=null)=>{setEditing({kind,item});setName(item?.name??'');setDetail(item?(kind==='locations'?(item as Location).address:(item as Category|Role).description):'');setError('')}
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!editing)return;setBusy(true);try{if(editing.kind==='locations'){const payload={name:name.trim(),address:detail.trim()};if(editing.item)await locationsApi.update(editing.item.id,payload);else await locationsApi.create(payload)}else{const payload={name:name.trim(),description:detail.trim()};const selectedApi=editing.kind==='categories'?categoriesApi:rolesApi;if(editing.item)await selectedApi.update(editing.item.id,payload);else await selectedApi.create(payload)}setEditing(null);await load()}catch(err){setError(err instanceof Error?err.message:'No se pudo guardar.')}finally{setBusy(false)}}
  const remove=async()=>{if(!deleting)return;setBusy(true);try{await api[deleting.kind].remove(deleting.item.id);setDeleting(null);await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo eliminar.')}finally{setBusy(false)}}
  const list=(kind:Kind,items:Item[],title:string,Icon:LucideIcon)=><section className="panel settings-panel"><div className="panel-heading"><div><h2><Icon size={16}/>{title}</h2><p>Opciones disponibles en el sistema.</p></div><button className="primary-button" onClick={()=>open(kind)}><Plus size={16}/>Nueva</button></div>{loading?<div className="loading-state">Cargando...</div>:<div className="settings-list">{items.map((item)=><div className="settings-row" key={item.id}><div><strong>{item.name}</strong><span>{kind==='locations'?(item as Location).address||'Sin dirección':(item as Category|Role).description||'Sin descripción'}</span></div><div className="settings-actions"><button className="icon-button" onClick={()=>open(kind,item)} aria-label="Editar"><Pencil size={15}/></button><button className="icon-button danger-icon" onClick={()=>setDeleting({kind,item})} aria-label="Eliminar"><Trash2 size={15}/></button></div></div>)}{!items.length&&<div className="empty-state">Sin registros.</div>}</div>}</section>
  const label=editing?.kind==='categories'?'categoría':editing?.kind==='locations'?'ubicación':'rol'
  return <div className="module-view settings-view"><section className="page-heading"><div><p className="eyebrow">Administración</p><h1>Configuración</h1><p className="intro">Catálogos globales disponibles para la operación.</p></div></section>{error&&!editing&&<p className="form-error page-error">{error}</p>}<div className="settings-grid settings-grid-three">{list('categories',categories,'Categorías',Tag)}{list('locations',locations,'Ubicaciones',MapPin)}{list('roles',roles,'Roles',ShieldCheck)}</div><Modal open={Boolean(editing)} title={`${editing?.item?'Editar':'Nueva'} ${label}`} onClose={()=>setEditing(null)}><form className="product-form" onSubmit={submit}><label><span>Nombre *</span><input required autoFocus value={name} onChange={(e)=>setName(e.target.value)}/></label><label><span>{editing?.kind==='locations'?'Dirección':'Descripción'}</span><textarea value={detail} onChange={(e)=>setDetail(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button className="secondary-button" type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?'Guardando...':'Guardar'}</button></div></form></Modal><ConfirmDialog open={Boolean(deleting)} message={`¿Eliminar ${deleting?.item.name??'este registro'}?`} busy={busy} onCancel={()=>setDeleting(null)} onConfirm={()=>void remove()}/></div>
}
