<?php
namespace App\Http\Controllers;
use App\Models\{Category, Client, InventoryMovement, Location, Product, ProductBatch, PurchaseOrder, Role, Service, Supplier, User};
use Illuminate\Http\JsonResponse;
class ApiController extends Controller
{
    protected function conflict(string $message): JsonResponse { return response()->json(['message' => $message], 409); }
    protected function role(Role $r): array { return ['id' => $r->id, 'name' => $r->name, 'description' => $r->description]; }
    protected function user(User $u): array { return ['id' => $u->id, 'name' => $u->full_name, 'email' => $u->email, 'role' => $u->role?->name, 'roleId' => $u->role_id, 'phone' => $u->phone ?? '', 'department' => $u->department ?? '', 'location' => $u->location ?? '', 'status' => $u->status, 'shift' => $u->shift ?? '', 'rating' => $u->rating === null ? 0 : (float) $u->rating, 'skills' => $u->skills ?? [], 'nextAssignment' => $u->next_assignment ?? '']; }
    protected function category(Category $c): array { return ['id' => $c->id, 'name' => $c->name, 'description' => $c->description]; }
    protected function location(Location $l): array { return ['id' => $l->id, 'name' => $l->name, 'address' => $l->address, 'active' => $l->active]; }
    protected function product(Product $p): array { $quantity=(float) $p->quantity; $minimum=(float) $p->minimum_quantity; return ['id' => $p->id, 'name' => $p->name, 'sku' => $p->sku, 'categoryId' => $p->category_id, 'category' => $p->category?->name, 'unit' => $p->unit, 'purchasePrice' => (float) $p->purchase_price, 'quantity' => $quantity, 'minimum' => $minimum, 'locationId' => $p->location_id, 'location' => $p->location?->name, 'status' => $quantity === 0.0 ? 'Agotado' : ($quantity <= $minimum ? 'Stock bajo' : 'En stock'), 'updatedAt' => $p->updated_at?->toISOString()]; }
    protected function supplier(Supplier $s): array { return ['id' => $s->id, 'name' => $s->name, 'category' => $s->category ?? '', 'contact' => $s->contact_name ?? '', 'phone' => $s->phone ?? '', 'email' => $s->email ?? '', 'rating' => $s->rating === null ? 0 : (float) $s->rating, 'status' => $s->status, 'productIds' => $s->products->pluck('id')->all(), 'products' => $s->products->pluck('name')->all()]; }
    protected function client(Client $c): array { return ['id' => $c->id, 'name' => $c->name, 'contact' => $c->contact_name ?? '', 'phone' => $c->phone ?? '', 'email' => $c->email ?? '', 'address' => $c->address ?? '']; }
    protected function service(Service $s): array { return ['id' => $s->id, 'folio' => $s->folio, 'title' => $s->title, 'clientId' => $s->client_id, 'client' => $s->client?->name ?? 'Sin cliente', 'location' => $s->location, 'scheduledAt' => $s->scheduled_at?->toISOString(), 'type' => $s->type, 'status' => $s->status, 'notes' => $s->notes ?? '', 'assignedUserIds' => $s->assignedUsers->pluck('id')->all(), 'assignedTo' => $s->assignedUsers->pluck('full_name')->all()]; }
    protected function movement(InventoryMovement $m): array { return ['id' => $m->id, 'folio' => $m->folio, 'type' => $m->type, 'reference' => $m->reference, 'origin' => $m->origin ?? '', 'status' => $m->status, 'date' => $m->movement_date?->toISOString(), 'supplierId' => $m->supplier_id, 'serviceId' => $m->service_id, 'user' => $m->creator?->full_name ?? '', 'reviewedBy' => $m->reviewed_by, 'reviewedAt' => $m->reviewed_at?->toISOString(), 'rejectionReason' => $m->rejection_reason, 'items' => $m->items->map(fn ($i) => ['productId' => $i->product_id, 'product' => $i->product?->name ?? '', 'category' => $i->product?->category?->name ?? '', 'quantity' => (float) $i->quantity, 'unit' => $i->product?->unit ?? ''])->all()]; }
    protected function batch(ProductBatch $b): array { return ['id'=>$b->id,'productId'=>$b->product_id,'product'=>$b->product?->name,'lotNumber'=>$b->lot_number,'serialNumber'=>$b->serial_number,'quantity'=>(float)$b->quantity,'expirationDate'=>$b->expiration_date?->toDateString(),'nextInspectionAt'=>$b->next_inspection_at?->toDateString(),'status'=>$b->status,'notes'=>$b->notes ?? '']; }
    protected function purchase(PurchaseOrder $o): array { return ['id'=>$o->id,'folio'=>$o->folio,'supplierId'=>$o->supplier_id,'supplier'=>$o->supplier?->name,'orderDate'=>$o->order_date?->toDateString(),'expectedDate'=>$o->expected_date?->toDateString(),'status'=>$o->status,'notes'=>$o->notes ?? '','total'=>(float)$o->total,'createdBy'=>$o->created_by,'approvedBy'=>$o->approved_by,'items'=>$o->items->map(fn($i)=>['id'=>$i->id,'productId'=>$i->product_id,'product'=>$i->product?->name,'orderedQuantity'=>(float)$i->ordered_quantity,'receivedQuantity'=>(float)$i->received_quantity,'pendingQuantity'=>(float)$i->ordered_quantity-(float)$i->received_quantity,'unitPrice'=>(float)$i->unit_price])->all()]; }
}
